config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('src.apps.main.urls', namespace='main')),
    path('create/', include('src.apps.registration.urls', namespace='create')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

src/apps/main/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from .views import ListRoom


app_name = 'main'

urlpatterns = [
    path('', ListRoom.as_view(), name='main_page'),
    path('room/', include('src.apps.room.urls', namespace='room')),
]

src/apps/registration/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from .views import SignUp

app_name = 'create'


urlpatterns = [
    path('account/', SignUp.as_view(), name='create_account'),
]

src/apps/room/urls.py
from django.urls import path
from .views import CreateRoom, DetailtRoom, CheckPassowrd, DeleteRoom

app_name = 'room'

urlpatterns = [
    path('<slug:slug>/id<int:pk>/', DetailtRoom.as_view(), name='detail_room'),
    path('<slug:slug>/id<int:pk>/checkpassword/', CheckPassowrd.as_view(), name='checkpassword'),
    path('<slug:slug>/id<int:pk>/delete/', DeleteRoom.as_view(), name='delete_room'),
    path('create/', CreateRoom.as_view(), name='create_new_room'),
]

src/models/message/models.py
from django.db import models
from django.conf import settings
from src.models.room.models import Room


class Message(models.Model):
    author          = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text            = models.TextField(blank=False)
    room            = models.ForeignKey(Room, on_delete=models.CASCADE)
    create_date     = models.DateTimeField(auto_now_add=True)

    


    def __str__(self):
        return f"{self.text}"

src/models/room/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Room(models.Model):
    ''' Модель создания комнаты  '''
    founder         = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='founder_room')
    name            = models.CharField(max_length=255, blank=False)
    password        = models.CharField(max_length=255, blank=False)
    slug            = models.SlugField()
    participants 	= models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='users_in_room')
    create_date     = models.DateTimeField(auto_now_add=True)


    def get_absolute_url(self):
        return reverse('main:room:detail_room', kwargs={'slug': self.slug, 'pk': self.pk})

    def get_delete_room(self):
        return reverse('main:room:delete_room', kwargs={'slug': self.slug, 'pk': self.pk})


    def __str__(self):
        return f"Комната {self.name}"


    class Meta:
        ordering = ['-create_date']



def pre_save_room_receiver(sender, instance, *args, **kwargs):
    slug = slugify(instance.name)
    instance.slug = slug


pre_save.connect(pre_save_room_receiver, sender=Room)

src/forms/room/forms.py
from django import forms
from src.models.room.models import Room
from django.contrib.auth.hashers import make_password


class FormRoom(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model   = Room
        fields  = [
            'name',
            'password',
        ]


    def clean_password(self):
        hashed_pswd = make_password(self.cleaned_data.get('password'))
        return hashed_pswd

src/apps/main/views.py
from django.views.generic.list import ListView
from src.models.room.models import Room


class ListRoom(ListView):

    model           = Room
    template_name   = 'main/index.html'


    def get_queryset(self):
        qs = self.request.GET.get('q')
        if qs is not None:
            return Room.objects.filter(name__icontains=qs)
        return Room.objects.all()

src/apps/room/views.py
from django.views.generic.edit import CreateView, DeleteView
from django.views import View
from django.http import Http404
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse, get_object_or_404
from src.forms.room.forms import FormRoom
from src.models.room.models import Room
from django.utils.text import slugify
from django.contrib.auth.hashers import check_password


class DeleteRoom(DeleteView):
    model           = Room
    template_name   = 'room/delete.html'
    success_url     = reverse_lazy('main:main_page')


    def get_object(self, queryset=None):
        obj = super(DeleteRoom, self).get_object(queryset=queryset)
        if obj.founder != self.request.user:
            raise Http404
        return obj



class CreateRoom(CreateView):
    queryset        = Room.objects.all()
    form_class      = FormRoom
    template_name   = 'room/create.html'

    def form_valid(self, form):
        form.instance.founder   = self.request.user
        return super().form_valid(form)



class CheckPassowrd(View):

    def get(self, request, *args, **kwargs):
        room = get_object_or_404(Room, pk=kwargs.get('pk'))
        if request.user in room.participants.all() or request.user == room.founder:
            return redirect(reverse('main:room:detail_room', kwargs={'slug': room.slug, 'pk': room.pk}))
        return render(request, 'room/check_password.html', {})

    def post(self, request, *args, **kwargs):
        room = get_object_or_404(Room, pk=kwargs.get('pk'))
        password    = request.POST.get('password')
        if check_password(password, room.password):
            room.participants.add(request.user)
            return redirect(reverse('main:room:detail_room', kwargs={'slug': room.slug, 'pk': room.pk}))
        return redirect('main:main_page')



class DetailtRoom(View):

    def get(self, request, *args, **kwargs):
        #room = Room.objects.get(pk=kwargs.get('pk'))
        room = get_object_or_404(Room, pk=kwargs.get('pk'))
        if self.request.user == room.founder or self.request.user in room.participants.all():
            return render(request, 'room/detail.html', {'room': room})
        else:
            return redirect(reverse('main:room:checkpassword', kwargs={'slug': room.slug, 'pk': room.pk}))

src/apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title> DERIDE YOU </title>
        <link rel="shortcut icon" href="{% static './assets/favicon.ico' %}" type="image/x-icon">
        <link href="https://fonts.googleapis.com/css?family=Mina:400,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static './css/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/typeit@5.10.7/dist/typeit.min.js"></script>
    </head>
    <body>
        {% block content %}

        {% endblock %}
    <script src="{% static './js/main.js' %}"></script>
    </body>
</html>

src/apps/templates/list_room.html
{% load static %}
<div class="list_room">

    {% if user.is_authenticated %}

    {% for ob in object_list %}
        <div class='view_room_in_main'>
            {% if user in ob.participants.all or user == ob.founder %}
                <img class='tick_mark' src="{% static './assets/tick.png' %}" />
            {% endif %}
            <p class='create_user'>create by: {{ob.founder.username}} <a href="{{ob.get_absolute_url}}">{{ob.name}}</a> at : <span>{{ob.create_date}}</span></p>
            <p class='count_participants_title'> users in room : <span class='count_participants'>{{ob.participants.count}}</span></p>
        </div>

    {% endfor %}
    {% else %}
        <div class='not_auth_container'>
            <p class='not_auth'>You must be logged in to see the list of rooms.</p>
            <img src="{% static './assets/sad.png' %}" />
        </div>
    {% endif %}

</div>

src/apps/templates/logout.html
<div class="logout_container">
    <a href="{% url 'logout' %}">logout</a>
</div>

src/apps/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'list_room.html' %}


    <div class="main_container">

        <img src="{% static './assets/anonymous-logo.png' %}" />

        {% if user.is_authenticated %}
            {% include 'logout.html' %}
            <h3 class='is_user'>Hi, <span>{{user.username}}.</span> How are you ?</h3>
            <p class='text-p'> Find a chat in which you are waiting or create and call friends. </p>

            <div class="search_room">
                <form>
                    <input type="text" name="q" placeholder="Search room ..." value="">
                </form>
            </div>

            <div class="create_room">
                <a href="{% url 'main:room:create_new_room' %}">create room</a>
            </div>

        {% else %}
            <h3 id='user_is_not'></h3>
            <div class="login_or_register">
                <a href="{% url 'login' %}">login</a>
                <a href="{% url 'create:create_account' %}">register</a>
            </div>
        {% endif %}

    </div>
<script src="{% static './js/text.js' %}"></script>
{% endblock %}

src/apps/templates/room/check_password.html
{% extends 'base.html' %}


{% block content %}

    <div class="check_password">

        <h3>Enter password to login.</h3>

        <form method="post">{% csrf_token %}
            <input type="password" placeholder="password ..." name="password" value="">
            <button type="submit" name="button">check</button>
        </form>
    </div>

{% endblock %}

src/apps/templates/room/create.html
{% extends 'base.html' %}


{% block content %}

<div class="form_create">
    <h2> Hi, {{user.username}}. Create your own room and chat. </h2>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
    <button type='submit'>create</button>
    </form>
</div>

{% endblock %}

src/apps/templates/room/delete.html
{% extends 'base.html' %}


{% block content %}
    <div class="delete_container">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object.name }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>

{% endblock %}

src/apps/templates/room/detail.html
{% extends 'base.html' %}


{% block content %}
    {% if user == room.founder %}
        <a class='btn_delete' href="{{room.get_delete_room}}">delete</a>
    {% endif %}
    <div class="room_detail">
        <h3>Hi, <span class='hi'>{{user.username}}</span>. You went into a room called <span class='name_room'>{{room.name}}</span></h3>
        <p>creator this room : <span class='creator'>{{room.founder.username}}</span></p>
    </div>


    <div class="chat_container">
        <div class="chat_logs">
            {% for comment in room.message_set.all  %}
                <div class="chat">
                    <div class="chat_user_info">{{comment.author}}</div>
                    <p class='chat_message'>{{comment.text}}</p>
                </div>
            {% endfor %}
        </div>

        <div class="chat_form">
            <form id='form_comment'>
                <input class='msg_form' type="text" name="" placeholder="Text ..." value="">
                <button type="subit" name="button">NEW</button>
            </form>
        </div>

    </div>


    <div class="list_users_in_room">
        <h4>Users in this room</h4>
        {% for user in room.participants.all %}
            <p>{{user.username}}</p>
        {% endfor %}
    </div>


<script type="text/javascript">


    let loc = window.location;
    let wsStart = 'ws://';
    if(loc.protocol == 'https:') {
        wsStart = 'wss://';
    }
    let endPoint = wsStart + loc.host + loc.pathname
    let wsMsg = new WebSocket(endPoint);
    wsMsg.onopen = function(e) {console.log("OpenMSG", e)}


    wsMsg.onmessage = function(e) {
        console.log("Message", e)
        let data = JSON.parse(e.data)
        $('.chat_logs')
            .append(`<div class="chat">
                    <div class="chat_user_info">${data['username']}</div>
                    <p class='chat_message'>${data['message']}</p>
                    </div>`);

    }




    $('#form_comment').on('submit', (e)=> {
        e.preventDefault();
        let text = $('.msg_form').val();
        if(text) {
            let data = {
                'message': text
            }
            wsMsg.send(JSON.stringify(data))
            $('#form_comment')[0].reset();
        }
    })




</script>





{% endblock %}